import React, { useState } from "react";
import { jsPDF } from "jspdf";

export default function Training() {
  const [topic, setTopic] = useState("");
  const [lesson, setLesson] = useState(null);
  const [loading, setLoading] = useState(false);

  // Grading State
  const [userCode, setUserCode] = useState("");
  const [feedback, setFeedback] = useState("");
  const [checking, setChecking] = useState(false);

  // 1. GENERATE LESSON
  const loadLesson = async () => {
    if (!topic.trim()) return;
    setLoading(true);
    setLesson(null);
    setFeedback("");
    setUserCode("");

    try {
      const res = await fetch("http://127.0.0.1:8000/api/lesson", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ topic: topic })
      });
      const data = await res.json();
      setLesson(data.lesson);
    } catch (err) {
      setLesson({ title: "Error", content: "Failed to connect.", exercise: "" });
    }
    setLoading(false);
  };

  // 2. CHECK CODE
  const checkCode = async () => {
    if (!userCode.trim()) return;
    setChecking(true);
    setFeedback("Thinking...");

    try {
      const res = await fetch("http://127.0.0.1:8000/api/check_exercise", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
            exercise_prompt: lesson.exercise,
            user_code: userCode
        })
      });
      const data = await res.json();
      setFeedback(data.feedback);
    } catch (err) {
      setFeedback("Error connecting to Tutor.");
    }
    setChecking(false);
  };

  // 3. EXPORT TO PDF (New Feature)
  const downloadPDF = () => {
    if (!lesson) return;

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const maxLineWidth = pageWidth - (margin * 2);

    // Header
    doc.setFontSize(22);
    doc.setTextColor(166, 107, 255); // Lumina Purple
    doc.text(lesson.title, margin, 20);

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100); // Grey
    doc.text("Generated by Lumina AI Tutor", margin, 26);

    // Content Line
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, 30, pageWidth - margin, 30);

    // Main Content
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0); // Black
    
    // Wrap text automatically
    const contentLines = doc.splitTextToSize(lesson.content, maxLineWidth);
    doc.text(contentLines, margin, 40);

    // Calculate position for Exercise based on how long content was
    const contentHeight = contentLines.length * 6; // Approx spacing
    let yPos = 40 + contentHeight + 15;

    // Check if we need a new page
    if (yPos > 250) {
        doc.addPage();
        yPos = 20;
    }

    // Exercise Section
    doc.setFontSize(14);
    doc.setTextColor(50, 50, 50);
    doc.text("Coding Challenge:", margin, yPos);

    yPos += 10;
    doc.setFont("courier"); // Monospace for code
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 150); // Dark Blue for code
    
    const exerciseLines = doc.splitTextToSize(lesson.exercise, maxLineWidth);
    doc.text(exerciseLines, margin, yPos);

    // Save File
    doc.save(`${lesson.title.replace(/\s+/g, '_')}_Lesson.pdf`);
  };

  return (
    <div style={{ padding: "50px", color: "white", maxWidth: "800px", margin: "0 auto", textAlign: "left" }}>
      <h1 style={{ marginBottom: "10px" }}>🐍 AI Python Tutor</h1>
      <p style={{ opacity: 0.7, marginBottom: "20px" }}>
        Interactive Coding Lessons. Powered by Local AI.
      </p>

      {/* SEARCH BAR */}
      <div style={{ display: "flex", gap: "10px", marginBottom: "30px" }}>
        <input 
          value={topic}
          onChange={(e) => setTopic(e.target.value)}
          placeholder="Topic (e.g. For Loops, Classes)..."
          style={{ flex: 1, padding: "15px", borderRadius: "10px", border: "1px solid #1e2a3e", background: "#0c1424", color: "white" }}
        />
        <button
          onClick={loadLesson}
          disabled={loading}
          style={{ padding: "0 30px", background: "#a66bff", borderRadius: "10px", border: "none", color: "white", fontWeight: "bold", cursor: "pointer" }}
        >
          {loading ? "Generating..." : "Start Lesson"}
        </button>
      </div>

      {/* LESSON CARD */}
      {lesson && (
        <div style={{ background: "#0c1424", padding: "30px", borderRadius: "15px", border: "1px solid #334155", position: "relative" }}>
          
          {/* PDF DOWNLOAD BUTTON */}
          <button 
            onClick={downloadPDF}
            style={{
                position: "absolute",
                top: "20px",
                right: "20px",
                padding: "8px 15px",
                background: "#f43f5e", // Red/Pink
                border: "none",
                borderRadius: "8px",
                color: "white",
                fontSize: "12px",
                fontWeight: "bold",
                cursor: "pointer"
            }}
          >
            📄 Save PDF
          </button>

          <h2 style={{ color: "#a66bff", marginTop: 0 }}>{lesson.title}</h2>
          <div style={{ lineHeight: "1.7", fontSize: "16px", whiteSpace: "pre-wrap" }}>
            {lesson.content}
          </div>

          <div style={{ marginTop: "30px", background: "#1e2a3e", padding: "20px", borderRadius: "10px" }}>
            <h4 style={{ margin: "0 0 10px 0", color: "#94a3b8" }}>💪 CHALLENGE:</h4>
            <div style={{ fontFamily: "monospace", color: "#e2e8f0", marginBottom: "15px" }}>
              {lesson.exercise}
            </div>

            <textarea
                value={userCode}
                onChange={(e) => setUserCode(e.target.value)}
                placeholder="Type your Python code here..."
                style={{
                    width: "100%", height: "150px", background: "#0f172a", color: "#a5b4fc",
                    fontFamily: "monospace", border: "1px solid #334155", borderRadius: "8px", padding: "10px", marginBottom: "10px"
                }}
            />
            
            <button
                onClick={checkCode}
                disabled={checking}
                style={{
                    padding: "10px 20px", background: "#22c55e", border: "none", borderRadius: "8px",
                    color: "white", fontWeight: "bold", cursor: "pointer"
                }}
            >
                {checking ? "Grading..." : "Run & Check Code"}
            </button>

            {feedback && (
                <div style={{ marginTop: "15px", padding: "15px", background: "#334155", borderRadius: "8px", borderLeft: "4px solid #a66bff" }}>
                    <strong>AI Tutor Feedback:</strong><br/>
                    {feedback}
                </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}